name: Déploiement sur VPS

on:
  push:
    branches:
      - main  # Changer si ton branche principale a un autre nom

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Connexion et Déploiement sur VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /chemin/vers/ton/projet
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          sudo systemctl restart php-fpm
          sudo systemctl restart nginx
